# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	config.vm.define "web" do |web|
		web.vm.box ="ubuntu/trusty64"
		web.vm.network "private_network", ip: "10.10.10.11"
		web.vm.network "forwarded_port", guest:80, host:8090
		web.vm.provision :shell, path: "web-bootstrap.sh"
		web.vm.provider "virtualbox" do |vbox|
        	vbox.memory = 128
			vbox.cpus = 1
		end
	end

	config.vm.define "db" do |db|
		db.vm.box ="puphpet/centos65-x64"
		db.vm.network "private_network", ip: "10.10.10.12"
		db.vm.provision :shell, path: "db-bootstrap.sh"
		
		db.vm.provider "virtualbox" do |vbox|
        	vbox.memory = 512
			vbox.cpus = 1
			vbox.gui = true
		end
	end

end
